### ISSUE TITLE
Anderson does not use relaxation factor

### ISSUE THREAD

**Issue by longemen3000** [JuliaNLSolvers/NLSolvers.jl#46]
seems that `beta` is set to `nothing` instead of being `beta = method.beta` ?
https://github.com/JuliaNLSolvers/NLSolvers.jl/blob/1ade351ae2f5c0c51e77023bf852ad7f7b4cd7e9/src/fixedpoints/anderson.jl#L89

**Comment by ararslan** [comment]
Seems this was fixed by #47
